---

- name: Starting Cassandra Servce If not running
  service: name=cassandra state=started
  become: true
  become_user: root
  register: start_result
  tags: cassandra-start
- debug: var=start_result
