---
- name: Check if Apache Cassandra already Exists
  stat: path=/opt/xcal/apps/apache-cassandra-{{ ac_version }}
  register: install_version
  failed_when: install_version.stat.exists == true
  tags: 
     - checkinstall
#- debug: var=install_version

- name: Downloading Apache Binaries to LOCAL
  copy: src={{ cassandra_repo }}/binaries/apache-cassandra-{{ ac_version }}-bin.tar.gz dest=/opt/xcal/apps/ owner=xdeploy group=xdeploy
  tags:
     - download

- name: Unzip Apache Binaries
  unarchive: src=/opt/xcal/apps/apache-cassandra-{{ ac_version }}-bin.tar.gz dest=/opt/xcal/apps/ copy=no owner=xdeploy group=xdeploy mode=0755
  tags:
     - unzip

- name: Creating a apache Soft Link
  file: src=/opt/xcal/apps/apache-cassandra-{{ ac_version }} dest=/opt/xcal/apps/apache owner=xdeploy group=xdeploy state=link
  tags: 
     - sl

- name: Configuring Apache Cassandra init file
  template: src=ACcassandra.j2 dest=/etc/init.d/cassandra owner=xdeploy group=xdeploy mode=0755  
  become: true
  become_user: root
  tags: 
     - init

- name: Copying ALL Apache Maintenance Scripts
  copy: src={{ item }} dest=/opt/xcal/bin/ owner=xdeploy group=xdeploy mode=0755
  with_fileglob:
    - /opt/ansible/cassandra_repo/maintanence/ac_maintanence/*
  when: install_edition == 'ac' 
  tags: scripts

- name: copy Apache nodetool script
  template: src=nodetool.j2 dest=/opt/xcal/bin/nodetool  owner=xdeploy group=xdeploy mode=0755
  when: install_edition == 'ac'
  tags: nodetool
- name: copy Apache cqlsh3 script
  template: src=cqlsh3.j2 dest=/opt/xcal/bin/cqlsh3  owner=xdeploy group=xdeploy mode=0755
  when: install_edition == 'ac'

